### ISSUE TITLE
Encountering Missing Data Files During Code Replication

### ISSUE THREAD

**Issue by pansishun** [fanyan0411/DSGD#1]
Hello! I am very interested in your research work and have attempted to replicate your code. However, during the process, I noticed that the required data file `./data/cifar100_labelindex` seems to be missing. Could you please provide this data, or guide me where to download it? Thank you very much for your help and support.

**Comment by fanyan0411** [comment]
Hi! 

Thanks for your attention! We have uploaded the label_index files in ./data directory. 
If you want to select another label index randomly, please refer to the repository [https://github.com/brain-research/realistic-ssl-evaluation](url).

Additionally, we have updated our main.py file to include more specific parameter values for reproduction.

If you have another problem, feel free to contact us!
